### ISSUE TITLE
Update the Readme files with illustrations for the topic

### ISSUE THREAD

**Issue by owais4321** [MLSA-Mehran-UET/Learn-to-code-java#1]
In this project you see each folder has Readme some of the complete some or not so we want to complete Readme file for each topic in the repository. Readme file should contain the theoretical concept regarding the topic and should also help understand the code available in repository in a better way.

**Comment by jmrchelani** [comment]
Assign this to me, I will try my level best to elaborate and write really simplified documentation.

**Comment by owais4321** [comment]
Sure I am assigning this to you and I hope to see some wonderful contribution 
happy coding <3

**Comment by jmrchelani** [comment]
Thanks buddy, I will make sure its wonderful contribution <3

**Comment by jmrchelani** [comment]
a pull request has been made, please review it.

**Comment by jmrchelani** [comment]
General request to everybody, the Documentation is being handled so avoid writing README because that makes conflicts in between commits, If you want to help you can surely help by pulling request on my fork so I can format them and pull request over here.
