### ISSUE TITLE
Java StringBuilder and StringBuffers should be added!

### ISSUE THREAD

**Issue by anchal00** [MLSA-Mehran-UET/Learn-to-code-java#151]
i think it would be helpful ,if we can explain Difference between mutable and immutable objects in java with the help of Strings and StringBuilders etc. with examples and explanations
@owais4321  if you think this is good then i would love to work upon it

**Comment by owais4321** [comment]
@anchal00 good go for it 
happy coding <3

**Comment by anchal00** [comment]
@owais4321 cool working on it!

**Comment by anchal00** [comment]
@owais4321 i have added those files ...please review my  PR #152

**Comment by mursalfk** [comment]
@anchal00 Done. Thanks for contributing 👍
