### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by siraiwaqarali** [MLSA-Mehran-UET/Learn-to-code-java#24]
Write code for different sorting techniques in java and place them inside a folder Sorting.

**Comment by MohammadUzair1** [comment]
@owais4321 Assign me this

**Comment by owais4321** [comment]
@MohammadUzair1 I am assigning you this 
happy coding <3

**Comment by mursalfk** [comment]
We are already having a Sorting Folder and many people have contributed to it as well @MohammadUzair1
